// Objective-C API for talking to ChatBackend Go package.
//   gobind -lang=objc ChatBackend
//
// File is generated by gobind. Do not edit.

#ifndef __ChatBackend_H__
#define __ChatBackend_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* ChatBackendGreet(void);

#endif
