
// Objective-C API for talking to the following Go packages
//
//	ChatBackend
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ChatBackend_FRAMEWORK_H__
#define __ChatBackend_FRAMEWORK_H__

#include "ChatBackend.objc.h"
#include "Universe.objc.h"

#endif
